### ISSUE TITLE
Icrease text size on large devices

### ISSUE THREAD

**Issue by frunkad** [frunkad/ninja-website#2]
Add `@media` breakpoints in CSS for increasing `font-size` on larger devices.

**Comment by Nirajn2311** [comment]
Can I take this up?

**Comment by itsVagabond** [comment]
@frunkad can I work on it ?

**Comment by frunkad** [comment]
take it up @Nirajn2311

**Comment by Charuka09** [comment]
add @media queries 
for an example
@media screen and (max-width: 724px) 
    .card p{
       font-size: 15px;
    }
  }
here the font size of the p element in class card will be changed to 15 pixels when the width of the dives is getting smaller than 734 px.

for further reference check this out guys
https://www.w3schools.com/cssref/css3_pr_mediaquery.asp

**Comment by Nirajn2311** [comment]
@frunkad do you want the `font-size` to be increased for all html files. Also the `max-width` should be 992px, am I right or wrong?

**Comment by frunkad** [comment]
No, only index file is sufficient. And you can use `min-width: 992px` and then the increased font-size inside the braces.

**Comment by frunkad** [comment]
Closed with #5
